1.4.0 Adicionando produtos com assinatura e novo método de pagamento
LinkNacional/woocommerce-invoice-payment pull request #47
Opened 2024-04-04 18:21 UTC by GuilhermeLinkNacional

Ajuste em variáveis ​​de escape e métodos de requisição para aumentar a segurança;
Adição de modal para compartilhar link de fatura;
Adição de produtos com assinaturas recorrentes;
Adição de opção de vários métodos de pagamento.

2024-04-11 18:14 UTC, helonfranca02 approved these changes

2024-04-16 15:58 UTC, Abraao2005 approved these changes

2024-04-20 18:46 UTC, emanuellopess commented on CHANGELOG.md
> +### 1.4.0 - 04/04/2024
@GuilhermeLinkNacional Necessita seguir padrão das normativas, apenas um jogo da velha:

```
# 1.4.0 - 04/04/2024
* mudança 1
* mudança 2
```

2024-04-20 18:46 UTC, emanuellopess commented on README.txt
> +Tested up to: 6.4
@GuilhermeLinkNacional Necessita atualizar para 6.5

2024-04-20 18:47 UTC, emanuellopess commented on README.txt
> += 1.4.0 =
@GuilhermeLinkNacional Adicione a data de lançamento entre asterisco: **22/04/2024**

2024-04-20 18:50 UTC, emanuellopess commented on includes/class-wc-invoice-payment-subscription.php
> +            $invoice_id = $_POST['invoice_id'];
@GuilhermeLinkNacional Nunca adicione globais sem escapar ou sanitizar elas, nesse caso vale um sanitize_text_field

2024-04-20 18:51 UTC, emanuellopess requested changes
Faltam apenas poucos ajustes para lançar, irei apresentar. Por gentileza adiciona o modo de uso no README.md e no README.txt.

2024-04-22 19:51 UTC, GuilhermeLinkNacional commented
@emanuellopess Acredito ter finalizado as alterações.

2024-05-03 13:40 UTC, emanuellopess approved these changes

2024-05-03 13:40 UTC, merged